In [2]:
# import librarys that we need
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
# read the data that we need
df = pd.read_excel("nan_clear.xlsx")
df.head()

,Unnamed: 0,DATEPRD,NPD_WELL_BORE_CODE,NPD_FIELD_CODE,NPD_FACILITY_CODE,ON_STREAM_HRS,AVG_DOWNHOLE_PRESSURE,AVG_DOWNHOLE_TEMPERATURE,AVG_DP_TUBING,AVG_CHOKE_SIZE_P,AVG_WHP_P,AVG_WHT_P,DP_CHOKE_SIZE,BORE_OIL_VOL,BORE_GAS_VOL,BORE_WAT_VOL
0,4,2014-04-11,well1,3420717,369304,0.0,310.37614,96.87589,277.27826,1.215987,33.09788,10.47992,33.07195,0.0,0.0,0.0
1,5,2014-04-12,well1,3420717,369304,0.0,303.50078,96.92339,281.44744,3.087015,22.05334,8.70429,22.05334,0.0,0.0,0.0
2,6,2014-04-13,well1,3420717,369304,0.0,303.53481,96.95885,276.03200,1.962365,27.50281,9.42315,16.16326,0.0,0.0,0.0
3,7,2014-04-14,well1,3420717,369304,0.0,303.78228,96.96873,282.78676,0.000000,20.99552,8.13137,20.73712,0.0,0.0,0.0
4,8,2014-04-15,well1,3420717,369304,0.0,303.85821,97.02136,289.94067,31.141856,13.91754,8.49833,12.18153,0.0,0.0,0.0

In [5]:
# split data to train and test 
test = df.groupby(["NPD_WELL_BORE_CODE"]).get_group("well5")
test.head()

,Unnamed: 0,DATEPRD,NPD_WELL_BORE_CODE,NPD_FIELD_CODE,NPD_FACILITY_CODE,ON_STREAM_HRS,AVG_DOWNHOLE_PRESSURE,AVG_DOWNHOLE_TEMPERATURE,AVG_DP_TUBING,AVG_CHOKE_SIZE_P,AVG_WHP_P,AVG_WHT_P,DP_CHOKE_SIZE,BORE_OIL_VOL,BORE_GAS_VOL,BORE_WAT_VOL
0,4,2014-04-11,well1,3420717,369304,0.00,310.376140,96.875890,277.278260,1.215987,33.097880,10.479920,33.071950,0.00,0.00,0.00
1,5,2014-04-12,well1,3420717,369304,0.00,303.500780,96.923390,281.447440,3.087015,22.053340,8.704290,22.053340,0.00,0.00,0.00
2,6,2014-04-13,well1,3420717,369304,0.00,303.534810,96.958850,276.032000,1.962365,27.502810,9.423150,16.163260,0.00,0.00,0.00
3,7,2014-04-14,well1,3420717,369304,0.00,303.782280,96.968730,282.786760,0.000000,20.995520,8.131370,20.737120,0.00,0.00,0.00
4,8,2014-04-15,well1,3420717,369304,0.00,303.858210,97.021360,289.940670,31.141856,13.917540,8.498330,12.181530,0.00,0.00,0.00
741,746,2013-07-08,well2,3420717,369304,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.00
742,747,2013-07-09,well2,3420717,369304,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.00
743,749,2013-07-11,well2,3420717,369304,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.00
744,751,2013-07-13,well2,3420717,369304,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.00
745,752,2013-07-14,well2,3420717,369304,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,0.00
1900,1911,2008-02-12,well3,3420717,369304,11.50,308.055940,104.418090,201.250000,14.484431,106.805939,16.294718,92.475107,284.65,38888.67,385.01
1901,1912,2008-02-13,well3,3420717,369304,24.00,303.033518,105.402696,182.144942,22.832986,120.888576,53.374330,89.620148,1869.70,285246.16,7.13
1902,1913,2008-02-14,well3,3420717,369304,22.50,295.586061,105.775486,181.867887,31.249966,113.718175,72.737631,80.120465,3124.09,509954.88,1.16
1903,1914,2008-02-15,well3,3420717,369304,23.15,297.662702,105.751875,180.832060,28.518930,116.830642,69.995943,84.250990,2608.28,383426.67,0.97
1904,1915,2008-02-16,well3,3420717,369304,24.00,295.935519,105.811114,180.501045,30.227902,115.434474,71.518347,82.359026,3051.80,418474.00,4.89
4906,5014,2008-03-30,well4,3420717,369304,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.265990,0.00,0.00,0.00
4907,5060,2008-05-16,well4,3420717,369304,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,32.847460,0.00,0.00,0.00
4908,5064,2008-05-20,well4,3420717,369304,0.00,117.499290,19.174870,117.499290,0.000000,0.000000,0.000000,31.893670,0.00,0.00,0.00
4909,5100,2008-06-25,well4,3420717,369304,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.045290,0.00,0.00,0.00
4910,5102,2008-06-27,well4,3420717,369304,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.778050,0.00,0.00,0.00
7760,8023,2014-01-12,well5,3420717,369304,0.00,303.747100,98.701230,283.534860,1.181753,20.212240,8.395740,20.146020,0.00,0.00,0.00
7761,8024,2014-01-13,well5,3420717,369304,0.00,303.955410,98.733830,280.695050,1.197065,23.260360,6.327640,23.189020,0.00,0.00,0.00
7762,8025,2014-01-14,well5,3420717,369304,0.00,303.377050,98.791770,282.029910,1.125136,21.347140,6.829930,21.274680,0.00,0.00,0.00
7763,8026,2014-01-15,well5,3420717,369304,0.00,304.405040,98.102420,272.529550,2.610212,31.875490,7.686810,27.094350,0.00,0.00,0.00
7764,8027,2014-01-16,well5,3420717,369304,24.00,241.770858,104.898944,185.900111,8.660590,55.870746,16.900088,27.966259,351.05,52394.90,0.00